# Generated by Django 4.1.4 on 2022-12-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpost',
            name='tags',
        ),
    ]
