# Generated by Django 4.1.4 on 2022-12-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_head_image_petpost_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_top_image', models.CharField(max_length=200)),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField()),
                ('news_udate', models.CharField(max_length=200, null=True)),
                ('news_link', models.CharField(max_length=200)),
                ('news_authors', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
