# Generated by Django 4.1.4 on 2022-12-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_newsscrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'animal_categories',
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'hotel_categories',
            },
        ),
        migrations.CreateModel(
            name='SGIHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgi_hotel_link', models.CharField(max_length=255)),
                ('sgi_hotel_img_url', models.CharField(max_length=255)),
                ('sgi_hotel_name', models.CharField(max_length=50)),
                ('sgi_hotel_location', models.CharField(max_length=50)),
                ('sgi_hotel_explain', models.CharField(max_length=255)),
                ('sgi_hotel_score', models.IntegerField()),
                ('sgi_hotel_review_num', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.hotelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='KoreaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh_img_url', models.CharField(max_length=255)),
                ('kh_hotel_link', models.CharField(max_length=255)),
                ('kh_hotel_name', models.CharField(max_length=50)),
                ('kh_hotel_location', models.CharField(max_length=50)),
                ('kh_hotel_explain', models.CharField(max_length=255)),
                ('kh_hotel_score', models.FloatField()),
                ('kh_hotel_review_num', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.hotelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_animals_url', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True)),
                ('animals_img_url', models.CharField(max_length=255)),
                ('animals_small_kind', models.CharField(max_length=200)),
                ('animals_color', models.CharField(max_length=200)),
                ('animals_sex', models.CharField(max_length=200)),
                ('animals_year', models.IntegerField()),
                ('animals_spot', models.CharField(max_length=200)),
                ('animals_reception_date', models.CharField(max_length=200)),
                ('animals_character', models.CharField(max_length=200)),
                ('animals_center', models.CharField(max_length=200)),
                ('animals_call', models.CharField(max_length=200)),
                ('animals_location', models.CharField(max_length=200)),
                ('animals_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.animalcategory')),
            ],
        ),
    ]
