# Generated by Django 4.1.4 on 2022-12-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0006_animalcategory_hotelcategory_sgihotel_koreahotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowoffPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_title', models.CharField(max_length=100)),
                ('sp_content', models.TextField()),
                ('sp_thumnail', models.ImageField(blank=True, upload_to='pet/images/%Y/%m/%d/')),
                ('sp_postdate', models.DateTimeField(auto_now_add=True)),
                ('sp_update', models.DateTimeField(auto_now=True)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sp_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_title', models.CharField(max_length=100)),
                ('rp_content', models.TextField()),
                ('rp_thumnail', models.ImageField(blank=True, upload_to='pet/images/%Y/%m/%d/')),
                ('rp_postdate', models.DateTimeField(auto_now_add=True)),
                ('rp_update', models.DateTimeField(auto_now=True)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rp_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.category')),
            ],
        ),
    ]
