# Generated by Django 4.1.4 on 2022-12-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_showoffpost_recommendpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendpost',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='author_id',
            new_name='author',
        ),
    ]
