# Generated by Django 4.1.4 on 2022-12-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_rename_author_id_recommendpost_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_category',
            new_name='Recommend_category',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_content',
            new_name='Recommend_content',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_postdate',
            new_name='Recommend_postdate',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_thumnail',
            new_name='Recommend_thumnail',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_title',
            new_name='Recommend_title',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='rp_update',
            new_name='Recommend_update',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_category',
            new_name='ShowOff_category',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_content',
            new_name='ShowOff_content',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_postdate',
            new_name='ShowOff_postdate',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_thumnail',
            new_name='ShowOff_thumnail',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_title',
            new_name='ShowOff_title',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='sp_update',
            new_name='ShowOff_update',
        ),
    ]
