# Generated by Django 4.1.4 on 2022-12-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_rename_rp_category_recommendpost_recommend_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalcategory',
            options={'verbose_name_plural': 'save_animal_location_categories'},
        ),
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name_plural': 'Animals_save'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Animal_Category'},
        ),
        migrations.AlterModelOptions(
            name='koreahotel',
            options={'verbose_name_plural': 'Korea_Hotel'},
        ),
        migrations.AlterModelOptions(
            name='newsscrap',
            options={'verbose_name_plural': 'News_scrap'},
        ),
        migrations.AlterModelOptions(
            name='petpost',
            options={'verbose_name_plural': 'Pet_Post'},
        ),
        migrations.AlterModelOptions(
            name='recommendpost',
            options={'verbose_name_plural': 'Recommend_Post'},
        ),
        migrations.AlterModelOptions(
            name='sgihotel',
            options={'verbose_name_plural': 'SGI_Hotel'},
        ),
        migrations.AlterModelOptions(
            name='showoffpost',
            options={'verbose_name_plural': 'Show_Off_Post'},
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_postdate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_thumnail',
            new_name='thumnail',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='recommendpost',
            old_name='Recommend_update',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_postdate',
            new_name='postdate',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_thumnail',
            new_name='thumnail',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='ShowOff_update',
            new_name='update',
        ),
    ]
