# Generated by Django 4.1.4 on 2022-12-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_animalcategory_options_alter_animals_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showoffpost',
            old_name='postdate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='showoffpost',
            old_name='update',
            new_name='updated_at',
        ),
    ]
