# Generated by Django 4.1.4 on 2022-12-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_rename_postdate_showoffpost_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SaveAnimalCategory',
        ),
        migrations.AlterModelOptions(
            name='animalcategory',
            options={'verbose_name_plural': 'Animal_Category'},
        ),
        migrations.AlterModelOptions(
            name='saveanimalcategory',
            options={'verbose_name_plural': 'save_animal_location_categories'},
        ),
        migrations.AlterField(
            model_name='petpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.animalcategory'),
        ),
        migrations.AlterField(
            model_name='recommendpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.animalcategory'),
        ),
        migrations.AlterField(
            model_name='showoffpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.animalcategory'),
        ),
    ]
