# Generated by Django 4.1.4 on 2022-12-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_rename_category_saveanimalcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='animals_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.saveanimalcategory'),
        ),
    ]
