# Generated by Django 4.1.4 on 2022-12-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_postcategory_petpost_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post_Category'},
        ),
    ]
