# Generated by Django 4.1.4 on 2022-12-27 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0016_recommendpost_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='animals_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.saveanimalcategory'),
        ),
        migrations.AlterField(
            model_name='koreahotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.hotelcategory'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.animalcategory'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.postcategory'),
        ),
        migrations.AlterField(
            model_name='recommendpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.animalcategory'),
        ),
        migrations.AlterField(
            model_name='recommendpost',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.postcategory'),
        ),
        migrations.AlterField(
            model_name='sgihotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.hotelcategory'),
        ),
        migrations.AlterField(
            model_name='showoffpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showoffpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.animalcategory'),
        ),
        migrations.AlterField(
            model_name='showoffpost',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.postcategory'),
        ),
    ]
