# Generated by Django 4.1.4 on 2022-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_alter_animals_animals_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreahotel',
            name='kh_hotel_explain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sgihotel',
            name='sgi_hotel_explain',
            field=models.TextField(),
        ),
    ]
